module.exports = {
  CONFIG_FILE: 'prod',
  baseUrl: 'https://linemini-apps.retailstudio.jp/',
  apiBaseUrl: 'https://api.retailstudio.jp/api/v2/',
  apiImpBaseUrl: 'https://imp.retailstudio.jp/imp/',
  staticBaseUrl: 'https://static.retailstudio.jp/',
  // gtmId: 'GTM-TW54N6G',
  basicAuthName: 'test',
  basicAuthPass: 'testtest!',
  SENTRY_DSN: 'https://abd57287dd614e33a4c6bf5f8f7915fe@o1293859.ingest.sentry.io/6532516',
  chain: {
    osaki: {
      key: 'osaki',
      id: 2,
      name: '大崎スーパー',
      showBalanceAtHome: true,
      clientKey: '2767127fb67c7bee738c520af4a558de',
      cardLength: 12,
    },
    'osaki-demo': {
      key: 'osaki-demo',
      id: 23,
      name: '大崎スーパーDEMO',
      showBalanceAtHome: true,
      clientKey: 'XXX',
      cardLength: 12,
    },
    'hankyu-oasis': {
      key: 'hankyu-oasis',
      id: 6,
      name: '阪急オアシス',
      showBalanceAtHome: false,
      clientKey: 'ce65554dc941a7eb949d18a6d12a1079',
      cardLength: 11,
    },
    inageya: {
      key: 'inageya',
      id: 7,
      name: 'いなげや',
      showBalanceAtHome: false,
      clientKey: 'f4965472909f23ff1e32f5727e6651c5',
      cardLength: 13,
      multiCards: [
        {
          cardNumber: '^2',
          barcodeType: 'JAN',
          image: 'card-ing-fan.png',
        },
        {
          cardNumber: '^1',
          barcodeType: 'none',
          image: 'card-ing-fan-v.png',
        },
      ],
    },
    marukyu: {
      key: 'marukyu',
      id: 11,
      name: '丸久（アルク）',
      showBalanceAtHome: false,
      clientKey: '804467c1b524411aac556a76eddb1283',
      cardLength: 16,
    },
    maruilife: {
      key: 'maruilife',
      id: 12,
      name: 'マルイ',
      showBalanceAtHome: true,
      clientKey: '0b962ee0ed0532c82d208536769d2985',
      cardLength: 13,
      multiCards: [
        {
          cardNumber: '^280',
          barcodeType: 'none',
          image: 'mam-heart.png',
        },
        {
          cardNumber: '^281',
          barcodeType: 'none',
          image: 'mam-heart-jcb.png',
        },
      ],
    },
    delicia: {
      key: 'delicia',
      id: 13,
      name: 'デリシア',
      showBalanceAtHome: false,
      clientKey: '7d88259ab6b35cb1e4a195d1d70457bb',
      cardLength: 13,
    },
    'keisei-store': {
      key: 'keisei-store',
      id: 14,
      name: '京成ストア',
      showBalanceAtHome: false,
      clientKey: '29718072535dd684914be8c49f37cddf',
      cardLength: 7,
    },
    'shizutetsu-store': {
      key: 'shizutetsu-store',
      id: 17,
      name: 'しずてつストア',
      showBalanceAtHome: false,
      clientKey: '0d1d42b5f64eec31a514d3217b23fedf',
      cardLength: 9,
    },
    albis: {
      key: 'albis',
      id: 27,
      name: 'アルビス',
      showBalanceAtHome: false,
      clientKey: 'f50dd4615a3708ed2013baddf24f7bb4',
      cardLength: 15,
      multiCards: [
        {
          cardNumber: '^7',
          barcodeType: 'none',
          image: 'albis-ponta.png',
        },
        {
          cardNumber: '^8',
          barcodeType: 'none',
          image: 'albis-ponta-plus.png',
        },
      ],
    },
    'meidiya-store': {
      key: 'meidiya-store',
      id: 31,
      name: '明治屋ストアー',
      showBalanceAtHome: false,
      clientKey: 'ae5a05c37f4aa3315154a72b4cb5ad71',
      noCard: 1,
      navItems: ['home', 'chirashi'],
    },
    'entetsu-store': {
      key: 'entetsu-store',
      id: 28,
      name: '遠鉄ストア',
      showBalanceAtHome: false,
      clientKey: 'd6c20da50a319f2794720ffd2b75aa62',
      cardLength: 10,
    },
  },
}
